### ISSUE TITLE
Need to update to support latest fabric shim.

### ISSUE THREAD

**Issue by AlexMoudelos** [hyperledger/fabric-chaintool#31]

**Comment by ghaskins** [comment]
From Alex:

```
 ~/work/src/github.com/trial/registry $ make run-chaincode
cd scripts; ./run
Inside mainpanic: interface conversion: *main.Registry is not registry.CCInterface: missing method AddRecord
goroutine 1 [running]:
panic(0xa2b4c0, 0xc820125400)
    /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
hyperledger/cci/registry.(*factoryImpl).Create(0xe62558, 0xacdf60, 0xe62558, 0x0, 0x0, 0x0, 0x0)
    /home/alex/work/src/github.com/trial/registry/build/src/hyperledger/cci/registry/server-stub.go:48 +0x69
hyperledger/ccs/api.Create(0xb09c00, 0x8, 0xacdf60, 0xe62558, 0x0, 0x0, 0x0, 0x0)
    /home/alex/work/src/github.com/trial/registry/build/src/hyperledger/ccs/api/api.go:32 +0x1ae
hyperledger/ccs.(*stubHandler).addDispatcher(0xc820028460, 0xb09c00, 0x8, 0xacdf60, 0xe62558, 0x0, 0x0)
    /home/alex/work/src/github.com/trial/registry/build/src/hyperledger/ccs/entrypoint.go:99 +0x64
hyperledger/ccs.Start(0xc820166660, 0x0, 0x0)
    /home/alex/work/src/github.com/trial/registry/build/src/hyperledger/ccs/entrypoint.go:120 +0x206
main.main()
    /home/alex/work/src/github.com/trial/registry/src/chaincode/registry.go:375 +0x17c
Makefile:43: recipe for target 'run-chaincode' failed
make: *** [run-chaincode] Error 2
```

**Comment by ecb** [comment]
This isn't a bug in chaintool. This error occurs when your cci file declares a transaction or query but your go code doesn't provide an implementation. During deployment the chaintool generated code tries to build a dispatch table to link the generated stub to your implementation but fails to find one resulting in the panic you see. Please check your implementation to make sure all the declared interfaces are implemented.
